# Generated by Django 3.1.2 on 2024-02-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_url',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
