# Generated by Django 3.1.2 on 2024-02-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_highest_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='highest_bid_amount',
            new_name='highest_bid',
        ),
    ]
