# Generated by Django 3.1.2 on 2024-02-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20240204_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='highest_bid',
            new_name='highest_bid_amount',
        ),
    ]
