# Generated by Django 3.1.2 on 2024-02-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid_amount',
        ),
    ]
